### ISSUE TITLE
Run MSISE with user indiced

### ISSUE THREAD

**Issue by panagiotispir** [timduly4/pyglow#125]
Hello,
Have anyone tried to run MSISE with user indices?
I use the following code, 
```
from datetime import datetime, timedelta
import pyglow
lat = 40.
lon = -80.
alt = 250.
dn = datetime(2015, 3, 23, 15, 30)
pt = pyglow.Point(dn, lat, lon, alt, user_ind=True)
pt.apmsis=15.0
pt.f107a=124.49012345679012
pt.f107p=121.5
pt.run_msis()
```
and I get the following error

```
Traceback (most recent call last):
  File "/home/panos/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-f6eb87c49871>", line 1, in <module>
    pt.run_msis(version=2000)
  File "/home/panos/.local/lib/python3.6/site-packages/pyglow/pyglow.py", line 252, in run_msis
    version=version,
  File "/home/panos/.local/lib/python3.6/site-packages/pyglow/msis.py", line 53, in run
    48,
ValueError: 0-th dimension must be 7 but got 0 (not defined).
```

I tried to go step by step back, but I saw that all the parameters which are required from MSISE are given. The error seems to be on this "48" but I cannot understand why...
I I simply run MSISE without set user_ind, it is working properly.
Thanks in advance

**Comment by bharding512** [comment]
pt.apmsis needs to be a length-7 array (or list)

Try pt.apmsis = [15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0]

**Comment by panagiotispir** [comment]
Thanks a lot guys! Now I realize it!!
