### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ali-doona** [timduly4/pyglow#132]
Hi, 
I am trying to install pyglow in Ubuntu. But have these issues:
As instruction I did:
       ```
$ cd pyglow/
       $ make -C src/pyglow/models source
       $ python3 setup.py install --user
```
but receive this error
     `error: could not delete '/home/ali/.local/lib/python3.6/site-packages/pyglow/generate_kpap.py': Permission denied`
I cannot change the permission of this file. 
I did again install command with sudo
        ` $ sudo python3 setup.py install --user`
with a final message 
         `... All done!`
When running 
         ` $ python3 -m unittest test.test_suite_pyglow`
I receive this message:
          ```
  ======================================================================
            ERROR: test_suite_pyglow (unittest.loader._FailedTest)
            ----------------------------------------------------------------------
            ImportError: Failed to import test module: test_suite_pyglow
            Traceback (most recent call last):
             File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
              module = __import__(module_name)
             ModuleNotFoundError: No module named 'test.test_suite_pyglow'
             ----------------------------------------------------------------------
           Ran 1 test in 0.000s

            FAILED (errors=1)
            ----------------------------------------------------------
```
In responce to command :
    `python3 -c "import pyglow"`
I get:
    ```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
     File "/home/ali/.local/lib/python3.6/site-packages/pyglow/__init__.py", line 2, in <module>
       from .pyglow import __version__  # noqa F401
     File "/home/ali/.local/lib/python3.6/site-packages/pyglow/pyglow.py", line 5, in <module>
        from future import standard_library
     ModuleNotFoundError: No module named 'future'

```

What do you think the problem is?
Thanks

**Comment by bharding512** [comment]
I haven't seen this error before. Ubuntu should be fine.

It seems like a path issue, possibly because pyglow was installed with sudo. Can you manually delete the offending file (with sudo) and then try to install pyglow (without sudo)?

future is a listed requirement for installing pyglow. If you don't have it already installed then you could try "pip install future" or "pip3 install future" depending on your setup. 

You could also try without the --user flag. Or even try using pip ("pip install .")

**Comment by sandyfreelance** [comment]
I got past the "ModuleNotFoundError: No module named 'test.test_suite_pyglow' problem by running 'pytest' instead (https://github.com/timduly4/pyglow/pull/93), which seems to be a documentation lag in the Python3 port.
