### ISSUE TITLE
Provide fallback URLs for downloading 

### ISSUE THREAD

**Issue by timduly4** [timduly4/pyglow#37]
Currently, IRI 2012 is not available at http://spdf.gsfc.nasa.gov/pub/models/iri/iri2012/00_iri2012.tar.  We need to have a backup (e.g., http://irimodel.org/IRI-2012/00_iri2012.tar) and a fallback mechanism for downloading the model.

**Comment by jafulet** [comment]
Hello, I am trying to install pyglow, I already resolved all the library dependencies & compilers but when I started to install pyglow an error appeared, it seems to me that this is related to missing models from URLs, see below:

error: can't copy 'pyglow/models/dl_models/igrf11/igrf11py.so': doesn't exist or not a regular file
[generate_kpap.py] Generating geophysical indices table...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/__init__.py", line 1, in <module>
    from pyglow import Point, Line
  File "/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/pyglow.py", line 13, in <module>
    from get_kpap import get_kpap
  File "/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/get_kpap.py", line 8, in <module>
    GEOPHYSICAL_INDICES = generate_kpap.fetch()
  File "/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/generate_kpap.py", line 370, in fetch
    geophysical_indices = generate_kpap()
  File "/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/generate_kpap.py", line 163, in generate_kpap
    mtime_table = get_mtime_table()
  File "/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/generate_kpap.py", line 119, in get_mtime_table
    mtime_table[fn] = os.path.getmtime(fn)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/home/jfuentes/.local/lib/python2.7/site-packages/pyglow/dst/1957_1969'


Could you suggest me a solution please? I am new in this. Thank you.

**Comment by timduly4** [comment]
@jafulet This is a result of the IRI 2012 tar file not being available (http://spdf.gsfc.nasa.gov/pub/models/iri/iri2012/00_iri2012.tar).  I need to incorporate a backup URL in order to fallback for downloading.

**Comment by jafulet** [comment]
Dear Tim

I could install pyglow.
Thank your support.

Javier

Enviado desde mi iPhone

**Comment by jafulet** [comment]
Hi, Definitively pyglow was not well installed, it is not working as when trying to import IRI library, my code falls in an error. Please let me know when the URL will be available. Thanks

**Comment by jafulet** [comment]
Hi, Definitively pyglow was not well installed, it is not working as when trying to import IRI library, my code falls in an error. Please let me know when the URL will be available. Thanks

**Comment by timduly4** [comment]
Fixed in https://github.com/timduly4/pyglow/pull/39.

@jafulet , please try again and let me know if the issue has been fixed.

Thanks,
Tim
