### ISSUE TITLE
pyglow python3

### ISSUE THREAD

**Issue by bcurtiswx** [timduly4/pyglow#48]
Is pyglow python 3 compatible and if not, is it possible? if it is, here's some install issues for you:

```
$ ./pyglow_install.sh
python get_models.py
Traceback (most recent call last):
  File "get_models.py", line 3, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
make: *** [all] Error 1
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_py
creating build
creating build/lib
creating build/lib/pyglow
copying pyglow/get_apmsis.py -> build/lib/pyglow
copying pyglow/get_kpap.py -> build/lib/pyglow
copying pyglow/coord.py -> build/lib/pyglow
copying pyglow/__init__.py -> build/lib/pyglow
copying pyglow/generate_kpap.py -> build/lib/pyglow
copying pyglow/pyglow.py -> build/lib/pyglow
running install_lib
copying build/lib/pyglow/get_apmsis.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow
copying build/lib/pyglow/get_kpap.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow
copying build/lib/pyglow/coord.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow
copying build/lib/pyglow/__init__.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow
copying build/lib/pyglow/generate_kpap.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow
copying build/lib/pyglow/pyglow.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow
byte-compiling /home/bcurtis/.local/lib/python3.6/site-packages/pyglow/get_apmsis.py to get_apmsis.cpython-36.pyc
byte-compiling /home/bcurtis/.local/lib/python3.6/site-packages/pyglow/get_kpap.py to get_kpap.cpython-36.pyc
byte-compiling /home/bcurtis/.local/lib/python3.6/site-packages/pyglow/coord.py to coord.cpython-36.pyc
  File "/home/bcurtis/.local/lib/python3.6/site-packages/pyglow/coord.py", line 12
    print "hello from coord.py!"
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("hello from coord.py!")?

byte-compiling /home/bcurtis/.local/lib/python3.6/site-packages/pyglow/__init__.py to __init__.cpython-36.pyc
byte-compiling /home/bcurtis/.local/lib/python3.6/site-packages/pyglow/generate_kpap.py to generate_kpap.cpython-36.pyc
byte-compiling /home/bcurtis/.local/lib/python3.6/site-packages/pyglow/pyglow.py to pyglow.cpython-36.pyc
running install_data
copying pyglow/models/Makefile -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/get_models.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/dl_models/hwm07/dummy.txt -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/hwm07/hwm07e.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/hwm93/hwm93.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/hwm93/sig.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/igrf11/igrf11.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/igrf12/igrf12.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/iri12/delete_iriflip_comments.py -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/iri12/iridreg.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
copying pyglow/models/f2py/msis/nrlmsise00_sub.patch -> /home/bcurtis/.local/lib/python3.6/site-packages/pyglow_trash
error: can't copy 'pyglow/models/dl_models/igrf11/igrf11py.so': doesn't exist or not a regular file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bcurtis/.local/lib/python3.6/site-packages/pyglow/__init__.py", line 1, in <module>
    from pyglow import Point, Line
ImportError: cannot import name 'Point'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bcurtis/.local/lib/python3.6/site-packages/pyglow/__init__.py", line 1, in <module>
    from pyglow import Point, Line
ImportError: cannot import name 'Point'
```

**Comment by timduly4** [comment]
@bcurtiswx We are working on this-- see Pull Request https://github.com/timduly4/pyglow/pull/47.  We should upgrade to Python 3 soon.
